# Generated by Django 5.0 on 2025-07-04 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porteiro',
            options={'verbose_name': 'Porteiro', 'verbose_name_plural': 'Porteiros'},
        ),
        migrations.AlterModelTable(
            name='porteiro',
            table='porteiro',
        ),
    ]
